const picture=[
  { 
    image:'./images/pic1.jpg',
    height:'200px',
  },
  { 
    image:'./images/pic2.jpg',
    height:'300px',
  },
  { 
    image:'./images/pic3.jpg',
    height:'100px',
  },
  { 
    image:'./images/pic4.jpg',
    height:'240px',
  },
  { 
    image:'./images/pic5.jpg',
    height:'250px',
  },
  { 
    image:'./images/pic6.jpg',
    height:'260px',
  },
  { 
    image:'./images/pic7.jpg',
    height:'210px',
  },
  { 
    image:'./images/pic8.jpg',
    height:'200px',
  },
  { 
    image:'./images/pic9.jpg',
    height:'140px',
  },
  { 
    image:'./images/pic5.jpg',
    height:'250px',
  },
  { 
    image:'./images/pic6.jpg',
    height:'260px',
  },
  { 
    image:'./images/pic7.jpg',
    height:'210px',
  },
  { 
    image:'./images/pic8.jpg',
    height:'200px',
  },
  { 
    image:'./images/pic9.jpg',
    height:'140px',
  },
  
]